### ISSUE TITLE
Authorization issue

### ISSUE THREAD

**Issue by ghost** [solojungle/threads-ts#2]
Bro I have an issue while getting access token says redirect Uri is not authorized or something give my docs how to correct make api developers.facebook and making access token from it

**Comment by solojungle** [comment]
Hey @c-o-d-e-xx, thank you for you comment!

You should be able to add a redirect uri from the settings page in the FB developer panel. Let me know if this fixes your issue!

<img width="1511" alt="settings-page-fb" src="https://github.com/user-attachments/assets/5ed25774-ab04-450e-8ad6-c68a4e8f64b7">
